version: "1"
services:
  api:
    source: docker-compose.prod.yml
    service: api
  worker:
    source: docker-compose.prod.yml
    service: worker
    replicas: 5
  frontend:
    source: docker-compose.prod.yml  
    service: frontend
  redis:
    source: docker-compose.prod.yml
    service: redis
